name: checkout
on: [push]

jobs:
  checkout-and-display-files:
    runs-on: ubuntu-latest
    steps: 
      - name: list files before
        run: ls -al
      - name: checkout
        run: |
          git init
          git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
          git fetch origin 
          echo "_________"
          git branch
          echo "__________"
          git checkout main
        - name: list files after
          run: ls -al 
          
