name: first Workflow
on: [push]
jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "hello world"
      - name: multi line commands
        run: |
          node -v
          npm -v   
  parallel-job-macos:
    runs-on: macos-latest
    steps:
      - name: view sw version
        run: sw_vers
  dependent-job:
    runs-on: windows-latest
    needs: parallel-job-macos
    steps:
      - name: echo a string
        run: Write-Output "windows string dependent on run-shell-command job"
      - name: error task, commands are not correct
        run: doesnotexists                  




          
