name: runs on issue creation
on: [issues]

jobs: 
  check:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo $GITHUB_SHA
          echo $GITHUB_REF
          echo "new LIne___________"
      - uses: actions/checkout@v4
    
