name: test worrflow
on: [push]
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print hello 
        run: echo "HElloo"
      - name: ip read
        run: sudo ip a s
  second-job-parrallel:
    runs-on: windows-latest
    steps:
      - name: ip info
        run: ipconfig
