name: working dir & shells
on: [push]
jobs:
  display-wd-info:
    runs-on: ubuntu-latest
    steps:
      - name: wd path and list
        run: |
          pwd
          ls -al
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
 
  display-wd-info2:
    runs-on: ubuntu-latest
    steps:
      - name: know path before change
        run: pwd
        
      - name: change wd
        working-directory: /home/runner
        run: |
          pwd
      

  display-wd-info-WINDOWS:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
        
    needs: display-wd-info
    steps:
      - name: wd path and list
        run: |
          Get-Location
          dir
          Write-Output $env:GITHUB_SHA
          Write-Output $env:GITHUB_REPOSITORY
          Write-Output $env:GITHUB_WORKSPACE

  python-job:
    runs-on: windows-latest
    steps:
      - name: python script
        shell: python
        run: |
          import platform 
          print(platform.processor())
      
        
        
